count_types: # package types not in this list are counted as 'other'
  - script
  - effect
  - theme
  - extension
  - langpack
repos:
  -
    link: 'https://github.com/ReaTeam/ReaScripts'
    index: 'https://github.com/ReaTeam/ReaScripts/raw/master/index.xml'
    default: true
    disporder: 1
  -
    link: 'https://github.com/ReaTeam/JSFX'
    index: 'https://github.com/ReaTeam/JSFX/raw/master/index.xml'
    default: true
    disporder: 2
  -
    link: 'https://github.com/ReaTeam/Themes'
    index: 'https://github.com/ReaTeam/Themes/raw/master/index.xml'
    default: true
    disporder: 3
  -
    link: 'https://github.com/ReaTeam/LangPacks'
    index: 'https://github.com/ReaTeam/LangPacks/raw/master/index.xml'
    default: true
    disporder: 4
  -
    link: 'https://github.com/MichaelPilyavskiy/ReaScripts'
    index: 'https://github.com/MichaelPilyavskiy/ReaScripts/raw/master/index.xml'
    default: true
    disporder: 11
  -
    link: 'https://github.com/X-Raym/REAPER-ReaScripts'
    index: 'https://github.com/X-Raym/REAPER-ReaScripts/raw/master/index.xml'
    default: true
    disporder: 12
  -
    link: 'https://github.com/chtammik/chtammik_Reaper_Scripts'
    index: 'https://github.com/chtammik/chtammik_Reaper_Scripts/raw/master/index.xml'
  -
    link: 'https://github.com/EUGEN27771/ReaScripts'
    index: 'https://github.com/EUGEN27771/ReaScripts/raw/master/index.xml'
  -
    link: 'https://github.com/fernsehmuell/reaper_scripts'
    index: 'https://github.com/fernsehmuell/reaper_scripts/raw/master/index.xml'
  -
    link: 'https://github.com/mrlimbic/reascripts'
    index: 'https://github.com/mrlimbic/reascripts/raw/master/index.xml'
  -
    link: 'https://github.com/przemoc/REAPER-ReaScripts'
    index: 'https://github.com/przemoc/REAPER-ReaScripts/raw/master/index.xml'
  -
    link: 'https://github.com/X-Raym/MIDI-Makey-Makey'
    index: 'https://github.com/X-Raym/MIDI-Makey-Makey/raw/master/index.xml'
  -
    link: 'https://geraintluff.github.io/jsfx/'
    index: 'https://geraintluff.github.io/jsfx/index.xml'
  -
    link: 'https://github.com/nofishonfriday/ReaScripts'
    index: 'https://github.com/nofishonfriday/ReaScripts/raw/master/index.xml'
